# Form implementation generated from reading ui file 'cleint.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.setWindowTitle("Phoenix Messenger Client")
        MainWindow.resize(674, 563)
        MainWindow.setStyleSheet("font: 12pt \"Roboto\";")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 671, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.chat_tab = QtWidgets.QWidget()
        self.chat_tab.setObjectName("chat_tab")
        self.chat_text = QtWidgets.QTextEdit(parent=self.chat_tab)
        self.chat_text.setEnabled(False)
        self.chat_text.setGeometry(QtCore.QRect(-10, 0, 671, 431))
        self.chat_text.setStyleSheet("padding: 5px;\n"
"font-size: 14px;\n"
"font-weight: 300;")
        self.chat_text.setObjectName("chat_text")
        self.tabWidget.addTab(self.chat_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.settings_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 671, 431))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setStyleSheet("padding: 5px;")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.ipaddr_edit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.ipaddr_edit.setObjectName("ipaddr_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ipaddr_edit)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setStyleSheet("padding: 5px;")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.portserv_edit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.portserv_edit.setObjectName("portserv_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.portserv_edit)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setStyleSheet("padding: 5px;")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.nickname_edit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.nickname_edit.setObjectName("nickname_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nickname_edit)
        self.create_data_btn = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.create_data_btn.setStyleSheet("padding: 5px;")
        self.create_data_btn.setObjectName("create_data_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.create_data_btn)
        self.log_text = QtWidgets.QTextEdit(parent=self.formLayoutWidget)
        self.log_text.setEnabled(False)
        self.log_text.setObjectName("log_text")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.log_text)
        self.tabWidget.addTab(self.settings_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 460, 671, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.message_line = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.message_line.setStyleSheet("padding: 10px;\n"
"font-size: 16px;")
        self.message_line.setText("")
        self.message_line.setObjectName("message_line")
        self.horizontalLayout_3.addWidget(self.message_line)
        self.send_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.send_button.setStyleSheet("padding: 10px;\n"
"font-size: 16px;")
        self.send_button.setObjectName("send_button")
        self.horizontalLayout_3.addWidget(self.send_button)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 510, 671, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.connect_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.connect_btn.setStyleSheet("padding: 10px;\n"
"font-size: 14px;")
        self.connect_btn.setObjectName("connect_btn")
        self.horizontalLayout_4.addWidget(self.connect_btn)
        self.shutdown_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.shutdown_btn.setStyleSheet("padding: 10px;\n"
"font-size: 14px;")
        self.shutdown_btn.setObjectName("shutdown_btn")
        self.horizontalLayout_4.addWidget(self.shutdown_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chat_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:14px; font-weight:304; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-size:16px; font-weight:504;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chat_tab), _translate("MainWindow", "Чат"))
        self.label.setText(_translate("MainWindow", "IP адрес сервера"))
        self.label_2.setText(_translate("MainWindow", "Порт сервера"))
        self.label_3.setText(_translate("MainWindow", "Никнейм"))
        self.nickname_edit.setText(_translate("MainWindow", "PhoenixUser000"))
        self.create_data_btn.setText(_translate("MainWindow", "Создать данные\n"
"для подключения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("MainWindow", "Настройки"))
        self.send_button.setText(_translate("MainWindow", "Отправить"))
        self.connect_btn.setText(_translate("MainWindow", "Подключиться"))
        self.shutdown_btn.setText(_translate("MainWindow", "Отключиться"))
